// Auto-generated DSLX from P4 program
// Generated by p4c-dslx backend

const MAX_PACKET_BITS: u32 = u32:12000;
const MAX_TABLE_ENTRIES: u32 = u32:1024;

// ===== Type Definitions =====

pub struct Ethernet_t {
    dstAddr: u48,
    srcAddr: u48,
    etherType: u16,
    _valid: bool,
}

pub struct Headers {
    ethernet: Ethernet_t,
}

pub struct Metadata {
}

// ===== Standard Metadata =====

pub struct StdMeta {
    ingress_port: u9,
    egress_spec: u9,
    egress_port: u9,
    instance_type: u32,
    packet_length: u32,
    enq_timestamp: u32,
    enq_qdepth: u19,
    deq_timedelta: u32,
    deq_qdepth: u19,
    ingress_global_timestamp: u48,
    egress_global_timestamp: u48,
    mcast_grp: u16,
    egress_rid: u16,
    checksum_error: u1,
    parser_error: u32,
    priority: u3,
}

// ===== Parser =====

pub fn parser_state_start(packet: bits[MAX_PACKET_BITS], headers: Headers, meta: Metadata, offset: u32) -> (Headers, Metadata, u32) {
    // Extract headers.ethernet
    let dstAddr = packet[offset +: u48];
    let offset = offset + u32:48;
    let srcAddr = packet[offset +: u48];
    let offset = offset + u32:48;
    let etherType = packet[offset +: u16];
    let offset = offset + u32:16;
    let ethernet = Ethernet_t { dstAddr: dstAddr, srcAddr: srcAddr, etherType: etherType, _valid: true };
    let headers = Headers { ethernet: ethernet, ..headers };
    (headers, meta, offset)
}

pub fn parser_apply(packet: bits[MAX_PACKET_BITS]) -> (Headers, Metadata, u32) {
    // Initialize headers with all _valid = false
    let headers = zero!<Headers>();
    let meta = zero!<Metadata>();
    let offset = u32:0;

    // Call start state
    let (headers, meta, offset) = parser_state_start(packet, headers, meta, offset);
    (headers, meta, offset)
}

// ===== Control: MyIngress =====

pub fn NoAction(headers: Headers, meta: Metadata, std_meta: StdMeta) -> (Headers, Metadata, StdMeta) {
    (headers, meta, std_meta)
}

pub fn drop(headers: Headers, meta: Metadata, std_meta: StdMeta) -> (Headers, Metadata, StdMeta) {
    // TODO: mark_to_drop(std_meta)
    (headers, meta, std_meta)
}

pub fn forward(headers: Headers, meta: Metadata, std_meta: StdMeta, port: u9) -> (Headers, Metadata, StdMeta) {
    let std_meta = StdMeta { egress_spec: port, ..std_meta };
    (headers, meta, std_meta)
}

// ===== Table: dmac =====

pub struct dmac_entry_t {
    headers_ethernet_dstAddr: u48,
    action_id: u8,
    forward_port: u9,
    _valid: bool,
}

pub fn table_dmac_apply(headers: Headers, meta: Metadata, std_meta: StdMeta, entries: dmac_entry_t[MAX_TABLE_ENTRIES]) -> (Headers, Metadata, StdMeta) {
    let lookup_headers_ethernet_dstAddr = headers.ethernet.dstAddr;

    // Search entries with for-loop
    let (matched, match_idx, headers, meta, std_meta) = for (i, (matched, match_idx, headers, meta, std_meta)): (u32, (bool, u32, Headers, Metadata, StdMeta)) in u32:0..MAX_TABLE_ENTRIES {
        let entry = entries[i];
        if !matched && entry._valid {
            if entry.headers_ethernet_dstAddr == lookup_headers_ethernet_dstAddr {
                (true, i, headers, meta, std_meta)
            } else {
                (matched, match_idx, headers, meta, std_meta)
            }
        } else {
            (matched, match_idx, headers, meta, std_meta)
        }
    }(((false, u32:0, headers, meta, std_meta)));

    if matched {
        let entry = entries[match_idx];
        if entry.action_id == u8:0 {
            forward(headers, meta, std_meta, entry.forward_port)
        } else if entry.action_id == u8:1 {
            drop(headers, meta, std_meta)
        } else if entry.action_id == u8:2 {
            NoAction(headers, meta, std_meta)
        } else {
            (headers, meta, std_meta)
        }
    } else {
        // No match - execute default action or NoAction
        (headers, meta, std_meta)
    }
}

pub fn MyIngress_apply(headers: Headers, meta: Metadata, std_meta: StdMeta, dmac_entries: dmac_entry_t[MAX_TABLE_ENTRIES]) -> (Headers, Metadata, StdMeta) {
    let (headers, meta, std_meta) = table_dmac_apply(headers, meta, std_meta, dmac_entries);
    (headers, meta, std_meta)
}

// ===== Control: MyEgress =====

pub fn MyEgress_apply(headers: Headers, meta: Metadata, std_meta: StdMeta) -> (Headers, Metadata, StdMeta) {
    (headers, meta, std_meta)
}

// ===== Deparser =====

pub fn deparser_apply(headers: Headers) -> bits[MAX_PACKET_BITS] {
    let output = bits[MAX_PACKET_BITS]:0;
    let offset = u32:0;

    // Emit headers.ethernet if valid
    let (output, offset) = if headers.ethernet._valid {
        // Serialize header fields into output at current offset
        //   dstAddr: 48 bits
        let output = bit_slice_update(output, offset, headers.ethernet.dstAddr);
        let offset = offset + u32:48;
        //   srcAddr: 48 bits
        let output = bit_slice_update(output, offset, headers.ethernet.srcAddr);
        let offset = offset + u32:48;
        //   etherType: 16 bits
        let output = bit_slice_update(output, offset, headers.ethernet.etherType);
        let offset = offset + u32:16;
        (output, offset)
    } else {
        (output, offset)
    };


    output
}

// ===== Top-level Pipeline =====

pub fn pipeline(packet: bits[MAX_PACKET_BITS], std_meta: StdMeta, dmac_entries: dmac_entry_t[MAX_TABLE_ENTRIES]) -> (bits[MAX_PACKET_BITS], StdMeta) {
    // Step 1: Parse the packet
    let (headers, meta, _parse_offset) = parser_apply(packet);

    // Step 2: Ingress processing
    let (headers, meta, std_meta) = MyIngress_apply(headers, meta, std_meta, dmac_entries);

    // Step 3: Egress processing
    let (headers, meta, std_meta) = MyEgress_apply(headers, meta, std_meta);

    // Step 4: Deparse
    let output_packet = deparser_apply(headers);

    (output_packet, std_meta)
}

