// Auto-generated DSLX from P4 program
// Generated by p4c-dslx backend

const MAX_PACKET_BITS: u32 = u32:12000;
const MAX_TABLE_ENTRIES: u32 = u32:1024;

// ===== Type Definitions =====

pub struct Ethernet_t {
    dstAddr: u48,
    srcAddr: u48,
    etherType: u16,
    _valid: bool,
}

pub struct Ipv4_t {
    version: u4,
    ihl: u4,
    diffserv: u8,
    totalLen: u16,
    identification: u16,
    flags: u3,
    fragOffset: u13,
    ttl: u8,
    protocol: u8,
    hdrChecksum: u16,
    srcAddr: u32,
    dstAddr: u32,
    _valid: bool,
}

pub struct Standard_metadata_t {
    ingress_port: u9,
    egress_spec: u9,
    egress_port: u9,
    instance_type: u32,
    packet_length: u32,
    enq_timestamp: u32,
    enq_qdepth: u19,
    deq_timedelta: u32,
    deq_qdepth: u19,
    ingress_global_timestamp: u48,
    egress_global_timestamp: u48,
    mcast_grp: u16,
    egress_rid: u16,
    checksum_error: u1,
    parser_error: u32,
    priority: u3,
}

pub struct Headers {
    ethernet: Ethernet_t,
    ipv4: Ipv4_t,
}

pub struct Metadata {
}

// ===== Standard Metadata =====

pub struct StdMeta {
    ingress_port: u9,
    egress_spec: u9,
    egress_port: u9,
    instance_type: u32,
    packet_length: u32,
    enq_timestamp: u32,
    enq_qdepth: u19,
    deq_timedelta: u32,
    deq_qdepth: u19,
    ingress_global_timestamp: u48,
    egress_global_timestamp: u48,
    mcast_grp: u16,
    egress_rid: u16,
    checksum_error: u1,
    parser_error: u32,
    priority: u3,
}

// ===== Parser =====

pub fn parser_state_parse_ipv4(packet: bits[MAX_PACKET_BITS], headers: Headers, meta: Metadata, offset: u32) -> (Headers, Metadata, u32) {
    // Extract hdr.ipv4
    let version = packet[offset +: u4];
    let offset = offset + u32:4;
    let ihl = packet[offset +: u4];
    let offset = offset + u32:4;
    let diffserv = packet[offset +: u8];
    let offset = offset + u32:8;
    let totalLen = packet[offset +: u16];
    let offset = offset + u32:16;
    let identification = packet[offset +: u16];
    let offset = offset + u32:16;
    let flags = packet[offset +: u3];
    let offset = offset + u32:3;
    let fragOffset = packet[offset +: u13];
    let offset = offset + u32:13;
    let ttl = packet[offset +: u8];
    let offset = offset + u32:8;
    let protocol = packet[offset +: u8];
    let offset = offset + u32:8;
    let hdrChecksum = packet[offset +: u16];
    let offset = offset + u32:16;
    let srcAddr = packet[offset +: u32];
    let offset = offset + u32:32;
    let dstAddr = packet[offset +: u32];
    let offset = offset + u32:32;
    let hdr.ipv4 = Ipv4_t { version: version, ihl: ihl, diffserv: diffserv, totalLen: totalLen, identification: identification, flags: flags, fragOffset: fragOffset, ttl: ttl, protocol: protocol, hdrChecksum: hdrChecksum, srcAddr: srcAddr, dstAddr: dstAddr, _valid: true };
    let headers = Headers { ipv4: hdr.ipv4, ..headers };
    (headers, meta, offset)
}

pub fn parser_state_start(packet: bits[MAX_PACKET_BITS], headers: Headers, meta: Metadata, offset: u32) -> (Headers, Metadata, u32) {
    // Extract hdr.ethernet
    let dstAddr = packet[offset +: u48];
    let offset = offset + u32:48;
    let srcAddr = packet[offset +: u48];
    let offset = offset + u32:48;
    let etherType = packet[offset +: u16];
    let offset = offset + u32:16;
    let hdr.ethernet = Ethernet_t { dstAddr: dstAddr, srcAddr: srcAddr, etherType: etherType, _valid: true };
    let headers = Headers { ethernet: hdr.ethernet, ..headers };
    if hdr.ethernet.etherType == u16:2048 {
        parser_state_parse_ipv4(packet, headers, meta, offset)
    } else if hdr.ethernet.etherType == (u16:0 /* unsupported op */ u16:0) {
        (headers, meta, offset)
    }
}

pub fn parser_apply(packet: bits[MAX_PACKET_BITS]) -> (Headers, Metadata, u32) {
    // Initialize headers with all _valid = false
    let headers = zero!<Headers>();
    let meta = zero!<Metadata>();
    let offset = u32:0;

    // Call start state
    let (headers, meta, offset) = parser_state_start(packet, headers, meta, offset);
    (headers, meta, offset)
}

// ===== Control: MyIngress =====

pub fn NoAction(headers: Headers, meta: Metadata, std_meta: StdMeta) -> (Headers, Metadata, StdMeta) {
    (headers, meta, std_meta)
}

pub fn drop(headers: Headers, meta: Metadata, std_meta: StdMeta) -> (Headers, Metadata, StdMeta) {
    // TODO: mark_to_drop(std_meta)
    (headers, meta, std_meta)
}

pub fn ipv4_forward(headers: Headers, meta: Metadata, std_meta: StdMeta, dstAddr: u48, port: u9) -> (Headers, Metadata, StdMeta) {
    let std_meta = Standard_metadata_t { egress_spec: port, ..std_meta };
    let hdr.ethernet = Ethernet_t { srcAddr: hdr.ethernet.dstAddr, ..hdr.ethernet };
    let hdr = Headers { ethernet: hdr.ethernet, ..hdr };
    let hdr.ethernet = Ethernet_t { dstAddr: dstAddr, ..hdr.ethernet };
    let hdr = Headers { ethernet: hdr.ethernet, ..hdr };
    let hdr.ipv4 = Ipv4_t { ttl: (hdr.ipv4.ttl + u8:255), ..hdr.ipv4 };
    let hdr = Headers { ipv4: hdr.ipv4, ..hdr };
    (headers, meta, std_meta)
}

// ===== Table: ipv4_lpm =====

pub struct ipv4_lpm_entry_t {
    hdr_ipv4_dstAddr: u32,
    hdr_ipv4_dstAddr_mask: u32,
    action_id: u8,
    ipv4_forward_dstAddr: u48,
    ipv4_forward_port: u9,
    _valid: bool,
}

pub fn table_ipv4_lpm_apply(headers: Headers, meta: Metadata, std_meta: StdMeta, entries: ipv4_lpm_entry_t[MAX_TABLE_ENTRIES]) -> (Headers, Metadata, StdMeta) {
    let lookup_hdr_ipv4_dstAddr = hdr.ipv4.dstAddr;

    // Search entries with for-loop
    let (matched, match_idx, headers, meta, std_meta) = for (i, (matched, match_idx, headers, meta, std_meta)): (u32, (bool, u32, Headers, Metadata, StdMeta)) in u32:0..MAX_TABLE_ENTRIES {
        let entry = entries[i];
        if !matched && entry._valid {
            if (entry.hdr_ipv4_dstAddr & entry.hdr_ipv4_dstAddr_mask) == (lookup_hdr_ipv4_dstAddr & entry.hdr_ipv4_dstAddr_mask) {
                (true, i, headers, meta, std_meta)
            } else {
                (matched, match_idx, headers, meta, std_meta)
            }
        } else {
            (matched, match_idx, headers, meta, std_meta)
        }
    }(((false, u32:0, headers, meta, std_meta)));

    if matched {
        let entry = entries[match_idx];
        if entry.action_id == u8:0 {
            ipv4_forward(headers, meta, std_meta, entry.ipv4_forward_dstAddr, entry.ipv4_forward_port)
        } else if entry.action_id == u8:1 {
            drop(headers, meta, std_meta)
        } else if entry.action_id == u8:2 {
            NoAction(headers, meta, std_meta)
        } else {
            (headers, meta, std_meta)
        }
    } else {
        // No match - execute default action or NoAction
        (headers, meta, std_meta)
    }
}

pub fn MyIngress_apply(headers: Headers, meta: Metadata, std_meta: StdMeta, ipv4_lpm_entries: ipv4_lpm_entry_t[MAX_TABLE_ENTRIES]) -> (Headers, Metadata, StdMeta) {
    if hdr.ipv4._valid {
        let (headers, meta, std_meta) = table_ipv4_lpm_apply(headers, meta, std_meta, ipv4_lpm_entries);
        (headers, meta, std_meta)
    } else {
        (headers, meta, std_meta)
    }
    // State from if/else merged above
    (headers, meta, std_meta)
}

// ===== Control: MyEgress =====

pub fn MyEgress_apply(headers: Headers, meta: Metadata, std_meta: StdMeta) -> (Headers, Metadata, StdMeta) {
    (headers, meta, std_meta)
}

// ===== Deparser =====

pub fn deparser_apply(headers: Headers) -> bits[MAX_PACKET_BITS] {
    let output = bits[MAX_PACKET_BITS]:0;
    let offset = u32:0;

    // Emit hdr.ethernet if valid
    if hdr.ethernet._valid {
        // Serialize header fields into output at current offset
        //   dstAddr: 48 bits
        let output = bit_slice_update(output, offset, hdr.ethernet.dstAddr);
        let offset = offset + u32:48;
        //   srcAddr: 48 bits
        let output = bit_slice_update(output, offset, hdr.ethernet.srcAddr);
        let offset = offset + u32:48;
        //   etherType: 16 bits
        let output = bit_slice_update(output, offset, hdr.ethernet.etherType);
        let offset = offset + u32:16;
        (output, offset)
    } else {
        (output, offset)
    }

    // Emit hdr.ipv4 if valid
    if hdr.ipv4._valid {
        // Serialize header fields into output at current offset
        //   version: 4 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.version);
        let offset = offset + u32:4;
        //   ihl: 4 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.ihl);
        let offset = offset + u32:4;
        //   diffserv: 8 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.diffserv);
        let offset = offset + u32:8;
        //   totalLen: 16 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.totalLen);
        let offset = offset + u32:16;
        //   identification: 16 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.identification);
        let offset = offset + u32:16;
        //   flags: 3 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.flags);
        let offset = offset + u32:3;
        //   fragOffset: 13 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.fragOffset);
        let offset = offset + u32:13;
        //   ttl: 8 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.ttl);
        let offset = offset + u32:8;
        //   protocol: 8 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.protocol);
        let offset = offset + u32:8;
        //   hdrChecksum: 16 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.hdrChecksum);
        let offset = offset + u32:16;
        //   srcAddr: 32 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.srcAddr);
        let offset = offset + u32:32;
        //   dstAddr: 32 bits
        let output = bit_slice_update(output, offset, hdr.ipv4.dstAddr);
        let offset = offset + u32:32;
        (output, offset)
    } else {
        (output, offset)
    }


    output
}

// ===== Top-level Pipeline =====

pub fn pipeline(packet: bits[MAX_PACKET_BITS], std_meta: StdMeta, ipv4_lpm_entries: ipv4_lpm_entry_t[MAX_TABLE_ENTRIES]) -> (bits[MAX_PACKET_BITS], StdMeta) {
    // Step 1: Parse the packet
    let (headers, meta, _parse_offset) = parser_apply(packet);

    // Step 2: Ingress processing
    let (headers, meta, std_meta) = MyIngress_apply(headers, meta, std_meta, ipv4_lpm_entries);

    // Step 3: Egress processing
    let (headers, meta, std_meta) = MyEgress_apply(headers, meta, std_meta);

    // Step 4: Deparse
    let output_packet = deparser_apply(headers);

    (output_packet, std_meta)
}

